image: ubuntu:14.04
stages:
  # - test
  - build
  # - deploy

cache:
  untracked: true
  paths:
  - vendor/

build:
  image: docker:git
  stage: build
  variables:
    DOCKER_DRIVER: overlay
    GETH_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $GETH_TAG -f Dockerfiles/Dockerfile-geth .
    - docker push $GETH_TAG
  only:
    - dev
    - tags
